name: AOT Checker

permissions:
  pull-requests: write

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build Sample
        run: dotnet build   samples/SunburstChartExample/ -c RELEASE -f net7.0 /p:PublishAot=true /p:SummaryOutDir=$GITHUB_WORKSPACE/summary
      - name: Publish Sample
        run: dotnet publish samples/SunburstChartExample/ -c RELEASE -f net7.0 /p:PublishAot=true /p:SummaryOutDir=$GITHUB_WORKSPACE/summary
      - name: Write summary
        run: |
          cd $GITHUB_WORKSPACE/summary
          echo '# AOT Output Information' >> $GITHUB_STEP_SUMMARY
          for FILE in *.log
          do
            echo ${FILE} >> $GITHUB_STEP_SUMMARY
          done
