name: AOT Checker

permissions:
  pull-requests: write

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build Sample
        run: cd samples/SunburstChartExample && dotnet build -c RELEASE
      - name: Publish Sample
        run: cd samples/SunburstChartExample && dotnet publish -c RELEASE -f net7.0 /p:PublishAot=true -o ./publish/sunburst
      - name: Write summary
        run: |
          echo '# Sunburst Sample:' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          ls publish/sunburst >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY